@baseUrl = http://localhost:7071
###
# @name simpleRequest
POST {{baseUrl}}/api/PostTrip/ HTTP/1.1
content-type: application/json

{
    "payload": {{$randomInt 0000001 100000}}
}
###
@Id = {{simpleRequest.response.body.id}}
# get order from ASP.NET endpoint
###
GET {{baseUrl}}/api/Test?name=Pippo


