@baseUrl = http://localhost:7071
###
# @name simpleRequest
POST {{baseUrl}}/api/PostTrip/ HTTP/1.1
content-type: application/json

{
    "payload": 233542151425
}
###
@Id = {{simpleRequest.response.body.id}}
# get order from ASP.NET endpoint
###
GET {{baseUrl}}/api/HttpTrigger1?name=Pippo